package juniper_test

import (
	"github.com/g-portal/switchmgr-go/pkg/vendors/juniper"
	"testing"
)

var runningConfigResponse = `<rpc-reply xmlns:junos="http://xml.juniper.net/junos/14.1X53/junos" message-id="a1318235-4751-408d-a7c0-066d652d7ac0" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
<data>
<configuration xmlns="http://xml.juniper.net/xnm/1.1/xnm" junos:commit-seconds="1664883144" junos:commit-localtime="2022-10-04 11:32:24 UTC" junos:commit-user="hcd">
    <version>14.1X53-D40.8</version>
    <system>
        <host-name>switch15_Frankfurt</host-name>
        <time-zone>UTC</time-zone>
        <root-authentication>
            <encrypted-password>$1$4AJN7gSc$hfrwjVzOlPWgymzzsbEwZ0</encrypted-password>
        </root-authentication>
        <name-server>
            <name>8.8.8.8</name>
        </name-server>
        <name-server>
            <name>8.8.4.4</name>
        </name-server>
        <login>
            <class>
                <name>config-readonly</name>
                <permissions>secret</permissions>
                <permissions>view-configuration</permissions>
                <allow-commands>show</allow-commands>
                <deny-commands>(clear)|(file)|(file show)|(help)|(load)|(monitor)|(op)|(request)|(save)|(set)|(start)|(test)</deny-commands>
            </class>
            <user>
                <name>awx</name>
                <uid>2005</uid>
                <class>config-readonly</class>
                <authentication>
                    <ssh-rsa>
<name>ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC7zF2IsFXcaLPHXZF8loPnrQIPYpiiIXCE5iarzYrXfzfrr4pgSlwRYoHiTCSYqaNHjhOPY5DG7fONRFhKCXQ7NxkU8Glqn6RInXe1m977+QrShOmaSj7nMCCy+Sww2yCfn5n3KucUEIcLNWrNA5Xg1W3/UutHRG6h7PU4SoHCiqYrgEXeAtIzr9F2aTLaLghJuydC/k3YkwpfRPg4Q/CuQfyN4RigqxBGavW33smyFitOZN8rBjjYpsHOFwI0OwLaw5hlW0xBLSlYikKFfuBmOwW6LPZuSXdA/83FyXcPsV9zdvkdh4pOvtiDgLmq8qQh87nqJyDm/xsDugiFG6yfIB1nVE+5XSha82YJfuBgKYdAs4gYlZ8y0noko10zmlkU/CIJdk3AWRlGp3os6Cvm6Od7JAUF9+CWktnhJZR5LRrrvLPB4QVEwMzrlAMURqu/cLhTK8TPTeI8vhXCN9Yu1VvWjwmH0nvYb0VH7pxRfhq398HHzIA4zU04Uvl8TQd7YcffYzoxCUgFiYaAlJLfiFAHgDvfSds1uD3F6bLT2KMHPZnLaM03O5cxQOInWzB0JfI1Qr61sSfHSQaVNeFjErSKBg74/xpF/S8Dn8HHunF9+Rv3Leg4UU8dm2Vo63SOgBiMYCiukXLoghU+reDpLWsRfcHB8w2zMfNLENrVjQ== gerrit@GamePC
                        </name>
                    </ssh-rsa>
                </authentication>
            </user>
            <user>
                <name>finest</name>
                <uid>2002</uid>
                <class>super-user</class>
                <authentication>
                    <ssh-rsa>
                        <name>ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAkhWzopXutgxkZskRTuLFOH21/asiIcHgSXtSdFS7Xbez5t9UB8lohYYGBzOcUKFDuLRcWSXY+vM9LJ9d3Dy26IwaWOvzbJlUybSyIMwft1F9V9CXffFB0/70lv/emab4SFlL4HtDnKFaNykyasQdTbdyJvT/CSXLyqz2V/GMnXJFG2H/zqE7MBz5t08jhJp5QneVwwd+1iETDph7HH0Ry8fqjQ0E7uySZtzOI/T0WpBbCvO9FCvLMY8v5KoddQiH1SeBNzsVLMVJxaGOmCzmvWkKBe0DuUxxfxF+euYXz8WW18Hb/2VdcZxMTnMIwFEDYuIwkLmJBAg/BdT/jGgmTw== michael@g-portal.com</name>
                    </ssh-rsa>
                </authentication>
            </user>
            <user>
                <name>gerrit</name>
                <uid>2000</uid>
                <class>super-user</class>
                <authentication>
                    <ssh-rsa>
<name>ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAgEAnxF/xYHZm4xaDfH5g3/H9fuN1aNPHaaeSA+xWOmF+vPoUjYnDqnS2ROBd5YLjnEbWYX+AK8SI3GXQM1+YRVo8XmUJmy1jPErTBcroIZ3H7QIGm6PkkI0IT05D5P3TNdZqVLIU6Xo2QBeoU+0+dG0Rv2bWrhlCNrRtjsectrLz18fR1yzSIE7++Mbu7tHjRNSIUNHKP3JtU9EIDK6Lcz+EQJY2EcOasAxQmetbaY/x+kAD3ld1Vct+cRm22cChFAZ+c4Vs6ynLBSNGulfHzBdJsTmGJoStn9H2Lo6PoaUaJY/SJOmZEGZNFvDjqYkI6YInNaHJ2klcDmVKAZkBNs0R0SOulxV1Thu6TMGj4yXGjydsO0HeuZjj0xCx+TOhGYdEudzPw+jB/ccA+YY+iB28nLqyA/my1CFdpeVYETQ40i9LC3FeyYyITbvfmxuU6GuwRqRvPwNqmCYsPO2siX8a98RzqgjlZdY9aTvG5KCae+ElK1i0vRTrO66J2fUOds+Vna+cxky95C5LYcRRNDe5Ad3uZIt3e6li7q6H4IH6gLrQDYyclap0YiO1+ZdxDvLQ7JUfXMewEE3Kax+uHsHAofq1I44p9ZczN+OP7tAzYztMDcJIvLYAGXMneFoXukqpAPrlgfbOXjLd36NY19Vj23345Ui4jHtuJbyNvwvICs= gerrit@gportal
                        </name>
                    </ssh-rsa>
                </authentication>
            </user>
            <user>
                <name>goas</name>
                <uid>2006</uid>
                <class>super-user</class>
                <authentication>
                    <ssh-rsa>
                        <name>ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEArWynIduRMiXPt0eNoCG3GvZYLbzDM22Ora28T7BU0DAEsWOlmicl+52oHVLmpWVyQ/ItdDzxYpqf8gmrrkExVgt8addk/q6RSa1jIlVN7RuB/0KgACa/kh8BD+fbKAbYAiqmPIb+a/4CKKo6TktlY66MXiZaIjCIPLtReXLbvNGiIH9Y8AasNIuAym77Y1D/3VAIYi6klls1Ki1xOuqZ7Ya0iWuf26IaCSOlevNNKvAiRv+kST5MnOLe/NBWLbCDAyH493o1KhMqSRBZ/y0vLI5dFEa1zIiEFNxjG4/QwzPkhU1f2l049sLDg0n28THVUVCRAGWgBW2qJJ2QIBSRTQ== Roberto Omezzolli</name>
                    </ssh-rsa>
                </authentication>
            </user>
            <user>
                <name>hcd</name>
                <uid>2003</uid>
                <class>super-user</class>
                <authentication>
                    <ssh-rsa>
<name>ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC5X4dOEcI12Bwff/T6ee6EdlrmXqNQaQIlqtgNVXYFj6SqLBXk4TjjQHTehS27rBS+sH4r1ai0OBpi8N0WEtT9hneibZ0v1rovovOkNQbXwO2r0w/kNY4OSUsnW+48WHJ1ty5oBnC+H59lcZMFRZfhe6br9+WbFARiwnf3qu/aUZ2pWf0vs0KzLi/O7pRgmljBx4Y2V02BwGzfqjIqtQMpF8zqUi/csH8pGeRBry2+vfr+RNKqE5sjdxiE2kngvsP/HO4kGGH88XY7+ZGuKVDX025Mi3kbY1JuxRjPQQHlZXAbb6EFSxDb+nNIyArzMzraIsVruerwe8kk91HZ/ZrjEX1M6bL8RQ/ZjDB9EmxGCbBFrv8+9085aMlIs9SgzZzQJPgQJdB2E4BYPL7D/rhI3rmD3DZQqD3uAdsA2i8xykd6CSYnHtyQbru8xUN1lW6N+YmEytfpcZd+VrhChvOEVdOzAj/YQB2xfQnrsYEC3c/sFt56QjT/40lTwELgkCtFHGFiFigFFU6alcxbPqnu2Zx5v5KJC7+dnF6OGJQ8RGchJhcn04IeBmTmtyfVTKq/omL+QE4Jo7Q60zNDub0TT0SrI1P0jCnf4X6LMHlckr5AyEuC7IwYwsTaP2Dirsxudk5jvj6CJvg8VEM/qwbgOsYgPOlxvJY/P4NB+5zpmw== ast@ast-desktop
                        </name>
                    </ssh-rsa>
                </authentication>
            </user>
            <user>
                <name>lama</name>
                <uid>2009</uid>
                <class>super-user</class>
                <authentication>
                    <encrypted-password>$1$Z8howHjf$Xg7lKkKaYuCVoFA7RgwLU.</encrypted-password>
                </authentication>
            </user>
            <user>
                <name>netbox</name>
                <uid>2007</uid>
                <class>read-only</class>
                <authentication>
                    <encrypted-password>$6$FojFNfNBpZwV8rNc$mAMfruDx2CigcopOt/2.Qbwy3hZS9DLCCrIj4GPm/m1xlI/8.0VJGvt2GfBjmCB4jNtElxE.fBbnwD9Eu.TD50</encrypted-password>
                    <ssh-rsa>
<name>ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCs64LCtMOMhYL1vJvSIKUCcS3MxL7WH2Jd7B/TrUihcjBuXZ6vk4uF6HlHGf5M5/UAaXwSTm5fP9sm0eVDceRQrF0p+riemLm6mE2vdkLfYW05Fl+TWoPW7C1mcfo/LiJIm0FbJaHti0xD+vtQTc1c78GRpaO0ijCP7D4+Wmz+DR6njBvmS/TtjZUqQncl41BPTDjnExU/AxbT+yVAEs0zRfDON7lKHVMhv8CqV+cWYYhLzyCl0Tff4X4Bq0ruRVMAcpjeIoA9oFQMi/GQsOZnhmQjQbQBnZeEKUqzTzP4SHXkpVD2TwLupQIb7iVHR6wuSTWQgEFSflH+HUxi9tdVtqyZe6oFB2WZIurPSfSJqQt2rFzXAxC9rrXNDKReflxU/E9Nq21dUCj/p6CYn3ltI6xKVm2wwVEyplXNH8+NPURM7WKu7ywcdsbWU/meqjjM/DHUGIHFxc45r3Wdf9SZ15J6j2qOOqBQzIPdmvyys/gYY4mMJtp97B/zThZxRpbd7JggAiD8cZukSxVZSlORKajTDRcD+UK6m5tzt96fs4A9HaIVwYPhef79Bg1VcZe9IANJNp24py9qMoy4N4pLrA3ojhIOseN8LtTnjujS4wf24xPPKFMw2gSkYCO6oIgKf1zh3zxmOUe1vp8SMO9EJvwnfFtF5pv9ReUR1T73dQ== netbox@switch
                        </name>
                    </ssh-rsa>
                </authentication>
            </user>
            <user>
                <name>tobili</name>
                <uid>2008</uid>
                <class>super-user</class>
                <authentication>
                    <ssh-rsa>
                        <name>ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEApmR56f0kyZV6XFvyisGnH84P67RDB3Trh7CQ41592Q3kKBtUqesXQ/u9Euagw2u7l9FSmfWpy7JB7Yihk0/50Nehcc7T4VAmYO6HyhcM+A7AYeWNmVm7cqokBNN42XIPqjlkdNoxarT1cx/ZX+pZnxbnGlOD52MUMhgKkRT7XrHhl1Hztr/5SBMDdXRWdT2wbq0c8lkJmLOxCwhBhPVjyK3DJcEx83KRC6xRBKSqtrrQAHD4T90GOGnRxM+GG+NmXLeEMjBryFSYtypATgIpNaXxXVctdNoOT+t8Zsp9kXuKctdIiB9FPbm0d7fLTSoq0m4mpk/Cqzm1OG0VMQoH/Q== Tobias Lindenberg</name>
                    </ssh-rsa>
                </authentication>
            </user>
            <user>
                <name>webinterface</name>
                <uid>2001</uid>
                <class>read-only</class>
                <authentication>
                    <encrypted-password>$1$mW5/FKFO$atuR9uXG/zb4CHJ6I01E9.</encrypted-password>
                </authentication>
            </user>
        </login>
        <services>
            <ssh>
                <root-login>allow</root-login>
                <protocol-version>v2</protocol-version>
            </ssh>
            <netconf>
                <ssh>
                    <port>830</port>
                </ssh>
            </netconf>
            <web-management>
                <http>
                </http>
            </web-management>
            <dhcp>
                <traceoptions>
                    <file>
                        <filename>dhcp_logfile</filename>
                    </file>
                    <level>all</level>
                    <flag>
                        <name>all</name>
                    </flag>
                </traceoptions>
            </dhcp>
        </services>
        <syslog>
            <host>
                <name>graylog-input-udp.ext.g-portal.net</name>
                <contents>
                    <name>any</name>
                    <any/>
                </contents>
                <port>12501</port>
            </host>
        </syslog>
        <max-configuration-rollbacks>5</max-configuration-rollbacks>
        <ntp>
            <server>
                <name>216.239.35.0</name>
            </server>
            <server>
                <name>216.239.35.4</name>
            </server>
            <server>
                <name>216.239.35.8</name>
            </server>
            <server>
                <name>216.239.35.12</name>
            </server>
        </ntp>
    </system>
    <chassis>
        <alarm>
            <management-ethernet>
                <link-down>ignore</link-down>
            </management-ethernet>
        </alarm>
        <auto-image-upgrade/>
    </chassis>
    <security>
        <ssh-known-hosts>
            <host>
                <name>[54.93.249.28]:222</name>
                <ecdsa-sha2-nistp256-key>AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBF23VNAy5nMPsp/wwHn1Qs8cJur3XdhfBBFszXxnCI+suVH2aH5GNjAPfHzjmiOt8GFJxaz/YqTPTjnD5Pw0yJs=;</ecdsa-sha2-nistp256-key>
            </host>
        </ssh-known-hosts>
    </security>
    <interfaces>
        <interface>
            <name>ge-0/0/0</name>
            <description>uplink</description>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <port-mode>trunk</port-mode>
                        <vlan>
                            <members>4</members>
                            <members>all</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/1</name>
            <description>bulwark-01_idrac</description>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <port-mode>trunk</port-mode>
                        <vlan>
                            <members>4</members>
                            <members>intern_daemon</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/2</name>
            <description>openshift-cluster</description>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <port-mode>trunk</port-mode>
                        <vlan>
                            <members>4</members>
                        </vlan>
                        <native-vlan-id>6</native-vlan-id>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/3</name>
            <description>openshift-cluster</description>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <port-mode>trunk</port-mode>
                        <vlan>
                            <members>4</members>
                        </vlan>
                        <native-vlan-id>6</native-vlan-id>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/4</name>
            <description>openshift-cluster</description>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <port-mode>trunk</port-mode>
                        <vlan>
                            <members>4</members>
                        </vlan>
                        <native-vlan-id>6</native-vlan-id>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/5</name>
            <description>openshift-cluster</description>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <port-mode>trunk</port-mode>
                        <vlan>
                            <members>4</members>
                        </vlan>
                        <native-vlan-id>6</native-vlan-id>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/6</name>
            <description>openshift-cluster</description>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <port-mode>trunk</port-mode>
                        <vlan>
                            <members>4</members>
                        </vlan>
                        <native-vlan-id>6</native-vlan-id>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/7</name>
            <description>openshift-cluster</description>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <port-mode>trunk</port-mode>
                        <vlan>
                            <members>4</members>
                        </vlan>
                        <native-vlan-id>6</native-vlan-id>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/8</name>
            <description>openshift-cluster</description>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <port-mode>trunk</port-mode>
                        <vlan>
                            <members>4</members>
                        </vlan>
                        <native-vlan-id>6</native-vlan-id>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/9</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <vlan>
                            <members>4</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/10</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <vlan>
                            <members>4</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/11</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <vlan>
                            <members>4</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/12</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <vlan>
                            <members>4</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/13</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <vlan>
                            <members>4</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/14</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <vlan>
                            <members>4</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/15</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <vlan>
                            <members>4</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/16</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <vlan>
                            <members>4</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/17</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <vlan>
                            <members>4</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/18</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <vlan>
                            <members>4</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/19</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <vlan>
                            <members>4</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/20</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <vlan>
                            <members>4</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/21</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <vlan>
                            <members>4</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/22</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <vlan>
                            <members>4</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/23</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <vlan>
                            <members>4</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/24</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <vlan>
                            <members>4</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/25</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <vlan>
                            <members>4</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/26</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <vlan>
                            <members>4</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/27</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <vlan>
                            <members>4</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/28</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <vlan>
                            <members>4</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/29</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <vlan>
                            <members>4</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/30</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <vlan>
                            <members>4</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/31</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <vlan>
                            <members>4</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/32</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <vlan>
                            <members>4</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/33</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <vlan>
                            <members>4</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/34</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <vlan>
                            <members>4</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/35</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <vlan>
                            <members>4</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/36</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <vlan>
                            <members>4</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/37</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <vlan>
                            <members>4</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/38</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <vlan>
                            <members>4</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/39</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <vlan>
                            <members>4</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/40</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <vlan>
                            <members>4</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/41</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <vlan>
                            <members>4</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/42</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <vlan>
                            <members>4</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/43</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <vlan>
                            <members>4</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/44</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <vlan>
                            <members>4</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/45</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <vlan>
                            <members>4</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/46</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <vlan>
                            <members>4</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/0/47</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <vlan>
                            <members>4</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/1/0</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>xe-0/1/0</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/1/1</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>xe-0/1/1</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/1/2</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>xe-0/1/2</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>ge-0/1/3</name>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                    </ethernet-switching>
                </family>
            </unit>
        </interface>
        <interface>
            <name>lo0</name>
            <unit>
                <name>0</name>
                <family>
                    <inet>
                        <filter>
                            <input>
                                <filter-name>protect-lo0</filter-name>
                            </input>
                        </filter>
                        <address>
                            <name>127.0.0.1/32</name>
                        </address>
                    </inet>
                </family>
            </unit>
        </interface>
        <interface>
            <name>vlan</name>
            <unit>
                <name>0</name>
                <family>
                    <inet>
                        <address>
                            <name>94.250.192.25/24</name>
                        </address>
                    </inet>
                </family>
            </unit>
        </interface>
    </interfaces>
    <snmp>
        <community>
            <name>gp_read</name>
            <authorization>read-only</authorization>
        </community>
    </snmp>
    <routing-options>
        <static>
            <route>
                <name>0.0.0.0/0</name>
                <next-hop>94.250.192.1</next-hop>
            </route>
        </static>
    </routing-options>
    <protocols>
        <igmp-snooping>
            <vlan>
                <name>all</name>
            </vlan>
        </igmp-snooping>
        <rstp>
        </rstp>
        <lldp>
            <interface>
                <name>all</name>
            </interface>
        </lldp>
        <lldp-med>
            <interface>
                <name>all</name>
            </interface>
        </lldp-med>
    </protocols>
    <policy-options>
        <prefix-list>
            <name>BGP-NEIGHBORS-v4</name>
            <apply-path>protocols bgp group &lt;*&gt; neighbor &lt;*.*&gt;</apply-path>
        </prefix-list>
        <prefix-list>
            <name>NTP-SERVERS-v4</name>
            <apply-path>system ntp server &lt;*.*&gt;</apply-path>
        </prefix-list>
        <prefix-list>
            <name>DNS-SERVERS-v4</name>
            <apply-path>system name-server &lt;*.*&gt;</apply-path>
        </prefix-list>
        <prefix-list>
            <name>lo0-allowed</name>
            <prefix-list-item>
                <name>5.45.104.235/32</name>
            </prefix-list-item>
            <prefix-list-item>
                <name>5.188.33.22/32</name>
            </prefix-list-item>
            <prefix-list-item>
                <name>5.188.34.25/32</name>
            </prefix-list-item>
            <prefix-list-item>
                <name>37.18.192.126/32</name>
            </prefix-list-item>
            <prefix-list-item>
                <name>38.39.199.90/32</name>
            </prefix-list-item>
            <prefix-list-item>
                <name>38.39.199.91/32</name>
            </prefix-list-item>
            <prefix-list-item>
                <name>43.251.182.25/32</name>
            </prefix-list-item>
            <prefix-list-item>
                <name>43.251.182.30/32</name>
            </prefix-list-item>
            <prefix-list-item>
                <name>45.35.136.143/32</name>
            </prefix-list-item>
            <prefix-list-item>
                <name>45.35.167.107/32</name>
            </prefix-list-item>
            <prefix-list-item>
                <name>45.35.204.0/24</name>
            </prefix-list-item>
            <prefix-list-item>
                <name>45.35.204.246/32</name>
            </prefix-list-item>
            <prefix-list-item>
                <name>45.35.204.249/32</name>
            </prefix-list-item>
            <prefix-list-item>
                <name>45.137.246.139/32</name>
            </prefix-list-item>
            <prefix-list-item>
                <name>45.137.246.140/32</name>
            </prefix-list-item>
            <prefix-list-item>
                <name>45.137.246.142/32</name>
            </prefix-list-item>
            <prefix-list-item>
                <name>45.137.247.139/32</name>
            </prefix-list-item>
            <prefix-list-item>
                <name>45.137.247.140/32</name>
            </prefix-list-item>
            <prefix-list-item>
                <name>45.137.247.142/32</name>
            </prefix-list-item>
            <prefix-list-item>
                <name>54.77.163.228/32</name>
            </prefix-list-item>
            <prefix-list-item>
                <name>54.171.227.230/32</name>
            </prefix-list-item>
            <prefix-list-item>
                <name>78.31.66.127/32</name>
            </prefix-list-item>
            <prefix-list-item>
                <name>94.250.192.0/19</name>
            </prefix-list-item>
            <prefix-list-item>
                <name>103.97.52.139/32</name>
            </prefix-list-item>
            <prefix-list-item>
                <name>103.97.52.140/32</name>
            </prefix-list-item>
            <prefix-list-item>
                <name>103.97.52.143/32</name>
            </prefix-list-item>
            <prefix-list-item>
                <name>116.202.24.146/32</name>
            </prefix-list-item>
            <prefix-list-item>
                <name>116.206.75.131/32</name>
            </prefix-list-item>
            <prefix-list-item>
                <name>146.185.218.138/32</name>
            </prefix-list-item>
            <prefix-list-item>
                <name>172.107.182.233/32</name>
            </prefix-list-item>
            <prefix-list-item>
                <name>172.107.182.235/32</name>
            </prefix-list-item>
            <prefix-list-item>
                <name>176.57.128.0/18</name>
            </prefix-list-item>
            <prefix-list-item>
                <name>185.137.120.0/22</name>
            </prefix-list-item>
            <prefix-list-item>
                <name>193.192.58.0/23</name>
            </prefix-list-item>
            <prefix-list-item>
                <name>193.200.241.140/32</name>
            </prefix-list-item>
            <prefix-list-item>
                <name>194.132.208.0/24</name>
            </prefix-list-item>
            <prefix-list-item>
                <name>205.204.92.248/32</name>
            </prefix-list-item>
            <prefix-list-item>
                <name>205.204.92.249/32</name>
            </prefix-list-item>
            <prefix-list-item>
                <name>205.204.92.250/32</name>
            </prefix-list-item>
        </prefix-list>
    </policy-options>
    <firewall>
        <family>
            <inet>
                <filter>
                    <name>protect-lo0</name>
                    <term>
                        <name>bgp</name>
                        <from>
                            <source-prefix-list>
                                <name>BGP-NEIGHBORS-v4</name>
                            </source-prefix-list>
                            <protocol>tcp</protocol>
                            <destination-port>bgp</destination-port>
                        </from>
                        <then>
                            <accept/>
                        </then>
                    </term>
                    <term>
                        <name>ssh</name>
                        <from>
                            <source-prefix-list>
                                <name>lo0-allowed</name>
                            </source-prefix-list>
                            <protocol>tcp</protocol>
                            <destination-port>ssh</destination-port>
                            <destination-port>830</destination-port>
                        </from>
                        <then>
                            <accept/>
                        </then>
                    </term>
                    <term>
                        <name>dns</name>
                        <from>
                            <source-prefix-list>
                                <name>DNS-SERVERS-v4</name>
                            </source-prefix-list>
                            <protocol>udp</protocol>
                            <source-port>53</source-port>
                        </from>
                        <then>
                            <accept/>
                        </then>
                    </term>
                    <term>
                        <name>ntp</name>
                        <from>
                            <source-prefix-list>
                                <name>NTP-SERVERS-v4</name>
                            </source-prefix-list>
                            <protocol>udp</protocol>
                            <source-port>123</source-port>
                        </from>
                        <then>
                            <accept/>
                        </then>
                    </term>
                    <term>
                        <name>snmp</name>
                        <from>
                            <source-prefix-list>
                                <name>lo0-allowed</name>
                            </source-prefix-list>
                            <protocol>udp</protocol>
                            <destination-port>161</destination-port>
                        </from>
                        <then>
                            <accept/>
                        </then>
                    </term>
                    <term>
                        <name>http</name>
                        <from>
                            <source-prefix-list>
                                <name>lo0-allowed</name>
                            </source-prefix-list>
                            <protocol>tcp</protocol>
                            <destination-port>80</destination-port>
                        </from>
                        <then>
                            <accept/>
                        </then>
                    </term>
                    <term>
                        <name>icmp</name>
                        <from>
                            <protocol>icmp</protocol>
                            <icmp-type>unreachable</icmp-type>
                            <icmp-type>time-exceeded</icmp-type>
                            <icmp-type>source-quench</icmp-type>
                        </from>
                        <then>
                            <accept/>
                        </then>
                    </term>
                    <term>
                        <name>icmp2</name>
                        <from>
                            <protocol>icmp</protocol>
                            <icmp-type>echo-request</icmp-type>
                            <icmp-type>echo-reply</icmp-type>
                        </from>
                        <then>
                            <accept/>
                        </then>
                    </term>
                    <term>
                        <name>traceroute</name>
                        <from>
                            <protocol>udp</protocol>
                            <destination-port>33434-33523</destination-port>
                        </from>
                        <then>
                            <accept/>
                        </then>
                    </term>
                    <term>
                        <name>localhost</name>
                        <from>
                            <source-address>
                                <name>127.0.0.1/32</name>
                            </source-address>
                            <destination-address>
                                <name>127.0.0.1/32</name>
                            </destination-address>
                        </from>
                        <then>
                            <accept/>
                        </then>
                    </term>
                    <term>
                        <name>ssh-config-archival</name>
                        <from>
                            <source-prefix-list>
                                <name>lo0-allowed</name>
                            </source-prefix-list>
                            <protocol>tcp</protocol>
                            <source-port>22</source-port>
                        </from>
                        <then>
                            <accept/>
                        </then>
                    </term>
                    <term>
                        <name>discard</name>
                        <then>
                            <discard>
                            </discard>
                        </then>
                    </term>
                </filter>
            </inet>
        </family>
    </firewall>
    <ethernet-switching-options>
        <storm-control>
            <interface>
                <name>all</name>
            </interface>
        </storm-control>
    </ethernet-switching-options>
    <vlans>
        <vlan>
            <name>bm-backend</name>
            <vlan-id>10</vlan-id>
        </vlan>
        <vlan>
            <name>bm-kvm</name>
            <vlan-id>2001</vlan-id>
        </vlan>
        <vlan>
            <name>bm-kvm-produktiv</name>
            <vlan-id>2011</vlan-id>
        </vlan>
        <vlan>
            <name>bm-provisioning</name>
            <vlan-id>2002</vlan-id>
        </vlan>
        <vlan>
            <name>bm-provisioning-produktiv</name>
            <vlan-id>2012</vlan-id>
        </vlan>
        <vlan>
            <name>bm-public</name>
            <vlan-id>2000</vlan-id>
        </vlan>
        <vlan>
            <name>bm-public-produktiv</name>
            <vlan-id>2010</vlan-id>
        </vlan>
        <vlan>
            <name>default</name>
        </vlan>
        <vlan>
            <name>intern_daemon</name>
            <vlan-id>6</vlan-id>
        </vlan>
        <vlan>
            <name>platform-mgmt</name>
            <vlan-id>4</vlan-id>
        </vlan>
        <vlan>
            <name>switch</name>
            <vlan-id>3</vlan-id>
            <l3-interface>vlan.0</l3-interface>
        </vlan>
    </vlans>
    <poe>
        <interface>
            <name>all</name>
        </interface>
    </poe>
</configuration>
</data>
</rpc-reply>
`

func TestParseRunningConfig(t *testing.T) {
	cfg, err := juniper.ParseRunningConfig([]byte(runningConfigResponse))
	if err != nil {
		t.Errorf("unexpected error: %s", err.Error())
	}
	if len(cfg.VLANs) != 11 {
		t.Errorf("expected model 11 vlans, got %d", len(cfg.VLANs))
	}
	if len(cfg.VLANs) != 11 {
		t.Errorf("expected model 11 vlans, got %d", len(cfg.VLANs))
	}
	expectedVlans := map[string]int32{
		"bm-backend":                10,
		"bm-kvm":                    2001,
		"bm-kvm-produktiv":          2011,
		"bm-provisioning":           2002,
		"bm-provisioning-produktiv": 2012,
		"bm-public":                 2000,
		"bm-public-produktiv":       2010,
		"default":                   0,
		"intern_daemon":             6,
		"platform-mgmt":             4,
		"switch":                    3,
	}
	for _, vlan := range cfg.VLANs {
		if desiredState, ok := expectedVlans[vlan.Name]; ok {
			if vlan.ID != desiredState {
				t.Errorf("vlan %s has wrong vlan-id, expected %d, got %d", vlan.Name, desiredState, vlan.ID)
			}
		} else {
			t.Errorf("vlan %s (%d) not found in expected vlans", vlan.Name, vlan.ID)
		}
	}
}
